---
name: Feature Branch Workflow | Terraform

on:
  push:
    branches-ignore:
      - main

jobs:
  flattened-terraform-f-workflow:
    name: Terraform Feature Branch Workflow
    uses: eingram-homelab/reusable-workflows/.github/workflows/_flattened-terraform-f-workflow.yaml@main
