---
name: Feature Branch Workflow | Terraform Module

on:
  push:
    branches-ignore:
      - main

jobs:
  flattened-terraform-f-workflow:
    name: Terraform Module Feature Branch Workflow
    uses: eingram-homelab/reusable-workflows/.github/workflows/_flattened-terraform-module-f-workflow.yaml@main
