---
name: Release Workflow | Terraform Module

on:
  push:
    branches:
      - main-test

permissions:
  contents: write

jobs:
  flattened-terraform-module-release-workflow:
    name: Terraform Module Release Workflow
    uses: eingram-homelab/reusable-workflows/.github/workflows/_flattened-terraform-module-release-workflow.yaml@add-terraform-module-workflows
